image: alpine/edge
oauth: pages.sr.ht/PAGES:RW
packages:
  - hut
environment:
  site: webring.gumx.cc
sources:
  - https://git.sr.ht/~gumxcc/webring.gumx.cc
tasks:
  - package: |
      cd webring.gumx.cc
      ./wr
      tar -C public -cvz . > ../site.tar.gz
  - upload: |
      hut pages publish -d $site site.tar.gz
